### ISSUE TITLE
what's the porpuse of this script?

### ISSUE THREAD

**Issue by berrytsakala** [BackSlasher/sgn-court-extract#1]
is it just for extracting the file(s)?
or it tries to do something else?
Do you know the file type of the signature <SignatureValue> ?
do you know how to use the <DigestValue> ?

**Comment by BackSlasher** [comment]
Hi :)
Is the relevant blog post helping?
https://blog.backslasher.net/sgn-extractor.html

**Comment by berrytsakala** [comment]
ok. got it.  It only extracts the file.
